//get the value guessed by the user as string
const userInput = document.getElementById("userGuess");

//generate a random number between 0 and 50
const computerNum = Math.floor(Math.random() * 51);

//get the result span
const resultOutput = document.getElementById("result");

//get the play game button
const playBtn = document.getElementById("playBtn");

//declare 3 attemps for the user
let userAttempts = 5;

//create a function to play the game that checks number inputted by the user and number of attemps
function playGame() {
  //convert the value guessed as string to number
  const userNum = Number(userInput.value);

  //if attemps are higher than 0, run a second if statment
  if (userAttempts > 0) {
    //if number imputted by user is equal to number generated by computer, display message below
    if (userNum === computerNum) {
      resultOutput.innerHTML = `You answered ${userNum} . This is the correct answer!`;
    }

    //if number imputted by user is higher to number generated by computer, display message below
    else if (userNum > computerNum) {
      resultOutput.innerHTML = `You answered ${userNum} . The correct answer is lower`;
      userAttempts--;
    }

    //if number imputted by user is lower to number generated by computer, display message below
    else {
      resultOutput.innerHTML = `You answered ${userNum} . The correct answer is higher`;
      userAttempts--;
    }
  }

  //if attemps are equal to zero dispay message below
  else if (userAttempts === 0) {
    resultOutput.innerHTML = `Sorry, no more attemps. The number was ${computerNum}`;
  }
}
playBtn.addEventListener("click", playGame);
